### ISSUE TITLE
Graph build failing in publish stage due to old Ensmallen error

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-ontoml#24]
Publishing the KG-Ontoml graph on Jenkins fails as follows:
```
20:06:27  + neat updateyaml --input_path neat.yaml --keys upload:s3_bucket_dir --values kg-ontoml/20220420/graph_ml/
20:06:31  Traceback (most recent call last):
20:06:31    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-ontoml_master/gitrepo/venv/bin/neat", line 11, in <module>
20:06:31      load_entry_point('neat==0.0.1', 'console_scripts', 'neat')()
20:06:31    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-ontoml_master/gitrepo/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
20:06:31      return get_distribution(dist).load_entry_point(group, name)
20:06:31    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-ontoml_master/gitrepo/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
20:06:31      return ep.load()
20:06:31    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-ontoml_master/gitrepo/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
20:06:31      return self.resolve()
20:06:31    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-ontoml_master/gitrepo/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
20:06:31      module = __import__(self.module_name, fromlist=['__name__'], level=0)
20:06:31    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-ontoml_master/gitrepo/venv/lib/python3.8/site-packages/neat/cli.py", line 4, in <module>
20:06:31      from ensmallen import Graph  # type: ignore
20:06:31    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-ontoml_master/gitrepo/venv/lib/python3.8/site-packages/ensmallen/__init__.py", line 13, in <module>
20:06:31      raise ValueError(
20:06:31  ValueError: This library was compiled assuming that SIMD instruction commonly available in CPU hardware since 2013 are present on the machine where this library is intended to run.
20:06:31  On the current machine, the flags {'avx2', 'bmi1', 'bmi2', 'avx'} are not available.
20:06:31  You could still compile Ensmallen on this machine and have a version of the library that can execute here, but the library has been extensively designed to use SIMD instructions, so you would have a version slower than the one provided on Pypi.
```

This happens because we call NEAT to use its yaml updating function, but NEAT is apparently using an antiquated version of Ensmallen that doesn't work without the right CPU flags.

This will be fixed by releasing a new version of NEAT compatible with more recent Ensmallen, but in the meantime the Jenkins build can install a more recent Ensmallen that NEAT will still tolerate.

**Comment by caufieldjh** [comment]
This still looks like it's failing immediately after the `neat updateyaml` call due to loading NEAT -> Ensmallen, then Ensmallen complains because the AVX flag isn't available. Options:
* Newer Ensmallen
* Don't use the `neat updateyaml` here, directly edit the file with awk/sed or something
